#include "main.h"

char HYDRA_VERSION_STRING[] = "2.0.1";
double CHASSIS_MAX_VELOCITY = 0.5;
double CHASSIS_MAX_ACCELERATION = 0.25;
double CHASSIS_MAX_JERK = 10.0;
double CHASSIS_WHEEL_DIAMETER = 0.08255;
double CHASSIS_WHEEL_TRACK = 0.24;
double CHASSIS_GEAR_RASIO = 1.667;
int PORT_LD_F = 11;
int PORT_RD_F = 19;
int PORT_LD_R = 12;
int PORT_RD_R = 20;
int PORT_LIFT = 3;
int PORT_TILTER = 9;
int PORT_INTAKE_L = 1;
int PORT_INTAKE_R = 10;
int PORT_TEST_MOTOR = 4;
int PORT_IMU = 13;

